### ISSUE TITLE
strtotime() is broken for certain dates

### ISSUE THREAD

**Issue by jetlej** [Shnoulle/Ar-PHP#1]
Hello! First off thank you for this amazing tool. FYI I don't speak Arabic

I just ran into an issue when using strrtotime() on this date: أبريل 1, 2016

The result is: 1470009600, which equates to: Sun Jul 31 2016 20:00:00 GMT-0400 (EDT)

So somehow it's converting April to July. 

Please help!

**Comment by Shnoulle** [comment]
Hi,

Must have an example PHP script. ANd i don't make support on this project, accept pull request. 
http://www.ar-php.org/I18N/Arabic/Examples/StrToTime.php

**Comment by Shnoulle** [comment]
https://github.com/tawfekov/ar-php seems better mantained (and have composer)
