### ISSUE TITLE
Need Persian Support

### ISSUE THREAD

**Issue by hosseinm1997** [Shnoulle/Ar-PHP#2]
Hi. I need persian support for these characters (ه گ چ پ ژ ی)
Note : The character (ی) is different from (ي) and is useful in persian. 
Please tell me what should I do? Thanks.

**Comment by Shnoulle** [comment]
No idea, maybe a fork .

**Comment by Shnoulle** [comment]
https://github.com/tawfekov/ar-php seems better maintained and have composer
